name: 'Run Terrafrom Apply'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Module'     
        required: false

jobs:
  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Not running on main or prod')
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: terraform_plan
        run: |
          if [ "${{ github.event.inputs.target }}" = "" ]; then
            echo "Running without target!"
            terraform plan -no-color -var "aws_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_key_secret=${{ secrets.AWS_KEY_SECRET }}" -out='plan.in'
          else
            echo "Running with target: ${{ github.event.inputs.target }}"
            terraform plan -no-color -var "aws_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_key_secret=${{ secrets.AWS_KEY_SECRET }}" -target="${{ github.event.inputs.target }}" -out='plan.in'
          fi
      - name: Wait 30s
        run: |
          sleep 30
      - name: Terraform apply
        id: apply
        run:  terraform apply -auto-approve -no-color -auto-approve plan.in