name: 'Run Terrafrom Plan'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform plan
        id: terraform_plan
        run: |
          echo "::set-value name=plan_output::$(terraform plan -var="aws_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_key_secret=${{ secrets.AWS_KEY_SECRET }}" -out="plan.in)"
      - name: Upload plan
        uses: actions/upload-artifact@v2
        with:
          name: tf-plan
          path: plan.in
      - name: Post PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Terraform Plan:
            
            ${{steps.terraform_plan.plan_output}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true
          

      

  