name: 'Run Terrafrom Plan'

on:
  push:
    branches:
      - "main"

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform plan
        id: terraform-plan
        run: terraform plan -var="aws_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_key_secret=${{ secrets.AWS_KEY_SECRET }}" -out="plan.in"
      - name: Upload plan
        uses: actions/upload-artifact@v2
        with:
          name: tf-plan
          path: plan.in
  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: apply-envoirnment
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Download plan
        uses: actions/download-artifact@v2
        with:
          name: tf-plan
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform apply
        id: apply
        run: terraform apply -no-color -auto-approve plan.in
      

  